# Generated by Django 4.1 on 2022-08-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="published_at",
            field=models.BooleanField(default=True),
        ),
    ]
