# Generated by Django 4.1 on 2022-08-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs_app", "0002_alter_vacancy_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="published_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
